# Generated by Django 3.1.2 on 2020-10-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeansPaymentOrder',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('means_payment', models.ForeignKey(db_column='id_means_payment', on_delete=django.db.models.deletion.DO_NOTHING, to='core.meanspayment')),
                ('order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
            ],
            options={
                'db_table': 'means_payment_order',
            },
        ),
    ]
