# Generated by Django 3.1.2 on 2020-10-13 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_meanspaymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOrderMeansPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Total order by means payment ',
                'verbose_name_plural': 'Total order by means payment ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.AlterModelOptions(
            name='meanspayment',
            options={'verbose_name': 'Means payment', 'verbose_name_plural': 'Means payments'},
        ),
        migrations.AlterModelOptions(
            name='meanspaymentorder',
            options={'verbose_name': 'Means payment order', 'verbose_name_plural': 'Means payment orders'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost price'),
        ),
        migrations.AlterField(
            model_name='meanspayment',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='meanspayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='meanspayment',
            name='description',
            field=models.CharField(error_messages={'unique': 'Means payment already exists'}, max_length=104, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meanspayment',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='meanspayment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='means_payment',
            field=models.ForeignKey(db_column='id_means_payment', on_delete=django.db.models.deletion.DO_NOTHING, to='core.meanspayment', verbose_name='Means payment'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='order',
            field=models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.DO_NOTHING, to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='meanspaymentorder',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Opened'), ('C', 'Closed'), ('X', 'Canceled'), ('P', 'Partial closed')], default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(db_column='id_table', on_delete=django.db.models.deletion.DO_NOTHING, to='core.table', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.DO_NOTHING, to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_description',
            field=models.TextField(blank=True, null=True, verbose_name='Detail description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=104, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='table',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='table',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('O', 'Occuped'), ('D', 'Desoccuped')], default='D', max_length=1, verbose_name='Status'),
        ),
    ]
