# Generated by Django 3.1.2 on 2020-10-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201013_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
    ]
