# Generated by Django 3.1.2 on 2020-10-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
